#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("QRScanExample.Resource", IsApplication=true)]

namespace QRScanExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::QRScanExample.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::QRScanExample.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::QRScanExample.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int fontWeight = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int id = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int image = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int isDefaultItem = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int name = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int tip = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int between_icon_text_padding = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int qr_scan_text_bottom_padding = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int small_text_size = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int qr_code_footer = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int qr_code_scan_frame = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int black = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int bold = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int condensed = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int contentFrame = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int italic = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int label = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int light = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int medium = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int overlay = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int regular = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int thin = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int QRScan = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int zxingscanneractivitylayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscannerfragmentlayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int qr_scan_tips = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int OverlayText = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int SmallOverlayText = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int VoiceTriggerStart = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
